sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.4.0-rc.1"
  - development
  
# matrix:
#   allow_failures:
#     - haxe: development
    
install:
  - haxelib install travix
  - haxelib install asys
  - haxelib install tink_io
  - haxelib git tink_unittest https://github.com/kevinresol/tink_unittest
  - haxelib run travix install

script:
  - haxelib run travix php -lib tink_unittest
  - haxelib run travix interp -lib tink_unittest
  - haxelib run travix neko -lib tink_unittest
  - haxelib run travix python -lib tink_unittest
  - haxelib run travix node -lib tink_unittest
  - haxelib run travix js -lib tink_unittest
  - haxelib run travix java -lib tink_unittest
  - haxelib run travix cs -lib tink_unittest
  - haxelib run travix php -lib tink_unittest -D openssl
  - haxelib run travix interp -lib tink_unittest -D openssl
  - haxelib run travix neko -lib tink_unittest -D openssl
  - haxelib run travix python -lib tink_unittest -D openssl
  - haxelib run travix node -lib tink_unittest -lib asys -D openssl
  - haxelib run travix java -lib tink_unittest -D openssl
  - haxelib run travix cs -lib tink_unittest -D openssl