sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  - haxelib run travix flash
  - haxelib run travix java
  - haxelib run travix cpp
  - if [ "${TRAVIS_HAXE_VERSION}" = "development" ]; then haxelib run travix cs; fi # bug on 3.2.1 fixed in dev
  # - haxelib run travix php (https://github.com/HaxeFoundation/haxe/issues/5015)