sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.4.2"
  - development
  
# matrix:
#   allow_failures:
#     - haxe: development
    
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix php
  - haxelib run travix interp
  - haxelib run travix neko
  # - haxelib run travix python
  - haxelib run travix node
  - haxelib run travix js
  - haxelib run travix java
  - haxelib run travix cs
  - haxelib run travix cpp
  # - haxelib run travix php -D openssl
  - haxelib run travix interp -D openssl
  - haxelib run travix neko -D openssl
  # - haxelib run travix python -D openssl
  # - haxelib run travix node -lib asys -D openssl
  - haxelib run travix java -D openssl
  # - haxelib run travix cs -D openssl
  - haxelib run travix cpp -D openssl