sudo: required
dist: trusty

language: node_js
node_js: 8

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
before_install:
  - args=()
  - if [[ "$(haxe -version)" =~ ^4.* ]]; then args+=(-lib); args+=(crypto); fi
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - lix run travix php "${args[@]}"
  - lix run travix interp "${args[@]}"
  - lix run travix neko "${args[@]}"
  - lix run travix python "${args[@]}"
  - lix run travix node "${args[@]}"
  - lix run travix js "${args[@]}"
  - lix run travix java "${args[@]}"
  - lix run travix cs "${args[@]}"
  - lix run travix cpp "${args[@]}"
  - lix run travix php -D openssl
  - lix run travix interp -D openssl
  - lix run travix neko -D openssl
  - lix run travix python -D openssl
  - lix run travix node -lib asys -D openssl
  - lix run travix java -D openssl
  - lix run travix cs -D openssl
  - lix run travix cpp -D openssl